spring:
  profiles:
    active: local
  mail:
    host: smtp.worksmobile.com
    port: 465
    properties:
      mail.smtp.auth: true
      mail.smtp.timeout: 5000
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: smtp.worksmobile.com
blocked:
  email-domains: []
